### ISSUE TITLE
Version should not be filled in unless listed as dynamic in pyproject.toml

### ISSUE THREAD

**Issue by bmerry** [mesonbuild/meson-python#454] opened 2023-08-22 08:59 UTC
According to [Declaring project metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata):

> If the metadata does not list a key in `dynamic`, then a build back-end CANNOT fill in the requisite metadata on behalf of the user (i.e. `dynamic` is the only way to allow a tool to fill in metadata and the user must opt into the filling in).

So if there is a `[project]` key in the pyproject.toml but `version` is not listed as dynamic, then I think mesonpy shouldn't be filling in the version from meson.build. If it's not listed either statically or dynamically, then the build should fail:

> If the [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata) specification lists a field as “Required”, then the metadata MUST specify the key statically or list it in dynamic (build back-ends MUST raise an error otherwise, i.e. it should not be possible for a required key to not be listed somehow in the [project] table).

Pragmatically, it might make more sense to have a period where mesonpy warns rather than giving a hard error, to give people a chance to fix up their projects.

**Comment by dnicolodi** [comment] 2023-08-22 09:56
Indeed, it seems that meson-python gets project name and version from `meson.build` only if `[project]` is missing: https://github.com/mesonbuild/meson-python/blob/ac8c940acb19f122d3f7461521d381d5a77ffa60/mesonpy/__init__.py#L721-L731

**Comment by bmerry** [comment] 2023-08-22 12:25
> Are you saying that meson-python gets the version from meson.build when a [project] section in pyproject.toml exist and version is not declared dynamic?

Yes, that is the behaviour I observed. I'll see if I can make a minimal reproducer.

**Comment by dnicolodi** [comment] 2023-08-22 12:45
Interesting. This is not the intended behavior. Thank you for the bug report. I'll look into fixing it.

**Comment by dnicolodi** [comment] 2023-08-22 13:03
It is a bug in `pyproject-metadata`: it automatically sets `version` to be a `dynamic` field if it is not explicitly set. I don't know why it does that. @FFY00 what is the reason for this behavior? My interpretation of the specification is the same as @bmerry, it is an error to do not have a `version` field without explicitly marking it as `dynamic`.

**Comment by dnicolodi** [comment] 2023-08-22 17:59
@bmerry PR #455 fixes the issue. We have a couple of other bugs to fix, thus I think there will be a new release relatively soon.

**Comment by rgommers** [comment] 2023-08-23 11:58
> thus I think there will be a new release relatively soon.

+1 - let's try to get that out the door very soon.

**Closed** 2023-08-25 10:11 UTC
Labels: bug
