### ISSUE TITLE
Build dependencies and editable wheels

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#278] opened 2023-01-28 20:47 UTC
Is it intended that build dependencies are not installed in the target environment when a project is installed as an editable wheel? This breaks the rebuild on import because the build dependencies are not found. PEP-660 does not contain any explicit information regarding this, other than:

> Build-backends must produce wheels that have the same dependencies (Requires-Dist metadata) as wheels produced by the build_wheel hook, with the exception that they can add dependencies necessary for their editable mechanism to function at runtime (such as [editables](https://pypi.org/project/editables/)).

I think we could interpret this to mean that we should append the build-requires dependencies to the editable wheel dependencies.

**Comment by rgommers** [comment] 2023-01-28 23:12
I think building in editable move means one should disable build isolation. It really does not make much sense to use build isolation for development work, and it actively breaks on rebuilds as you noticed.

> I think we could interpret this to mean that we should append the build-requires dependencies to the editable wheel dependencies.

If you mean "move build time dependencies to runtime dependencies", then that sounds unhealthy to me. It will lead to trying to install with pip into conda envs for one.

**Comment by dnicolodi** [comment] 2023-01-28 23:19
> If you mean "move build time dependencies to runtime dependencies", then that sounds unhealthy to me. It will lead to trying to install with pip into conda envs for one.

Despite using it on Windows, I'm not that familiar with Conda. How is adding the build dependencies to the runtime dependencies making adding any issue here? Installing the editable wheel will still try to resolve the dependencies with pip.

**Comment by rgommers** [comment] 2023-01-28 23:30
Ugh, you are right, it's already a problem for runtime dependencies (I don't use `pip` for dev work for a reason, so forgot about that). The correct way to use editable builds is this I'd say:
```
pip install -e . --no-build-isolation --no-deps
```

> How is adding the build dependencies to the runtime dependencies making adding any issue here?

In general you do not want to mix conda packages and wheels. So if you use a conda dev env, you may want the editable install of the package you're working on - but nothing else.

**Comment by rgommers** [comment] 2023-01-28 23:32
I'm not sure what the general answer is though. The `pip` UX is just poor for this. Before moving to Meson, I always used `python setup.py develop` (or `build_ext -i`), because that does the right thing.

**Comment by rgommers** [comment] 2023-01-30 10:53
> What does the editable installs PEP say about build isolation?

Absolutely nothing, not completely surprisingly.

> IMHO tools should automatically mandate disabling build isolation as an implicit consequence of using editable mode.

Agreed. I am not going to go out and propose that though, because I expect it to not be accepted - because things work smoothly with a discarded build env when you don't need to rebuild (i.e. for pure Python projects), and then non-isolated builds would be a slight regression in UX (there is no way to say "install build deps in existing env"). And also because using compiled code is "a special case".

**Comment by eli-schwartz** [comment] 2023-01-30 13:01
> And also because using compiled code is "a special case".

😂

**Comment by FFY00** [comment] 2023-01-30 19:11
> I think we could interpret this to mean that we should append the build-requires dependencies to the editable wheel dependencies.

Yes, this would be technically correct thing to do.

> I think building in editable move means one should disable build isolation. It really does not make much sense to use build isolation for development work, and it actively breaks on rebuilds as you noticed.

I agree. I don't think any package manager builds editable wheel in isolation, it wouldn't make sense. Hence this is basically a non-issue.

> If you mean "move build time dependencies to runtime dependencies", then that sounds unhealthy to me. It will lead to trying to install with pip into conda envs for one.

I mean, it would be the right thing to do from a correctness POV, but I personally think it'd cause more trouble than it's worth.

IMO the only situation it'd make sense for us to add dependencies to the editable wheel is if we had extra runtime dependencies that are not needed for the build, which we do not.

**Comment by FFY00** [comment] 2023-01-30 19:18
Oh, that's unfortunate. Well, I can see the benefit in simple backends, but for us is undesirable.

In that case, we should probably do it.

**Comment by rgommers** [comment] 2023-01-30 21:05
> I don't think any package manager builds editable wheel in isolation, it wouldn't make sense.

It seems like we all agree on this point, so maybe someone should point this out on the `pip` issue tracker if we want to do anything at all here. 

> In that case, we should probably do it.

If "it" means "add the build dependencies as runtime dependencies to the wheel", then I'm -1 on that. It's guaranteed to break things. That's not only easy to reason about, but I'm also 100% sure it will break for the recommended development setup of SciPy and other packages where people commonly use conda dev envs + using a `numpy ==` build dependency.

**Comment by rgommers** [comment] 2023-04-18 15:02
The doc rewrite in gh-389 addresses this now, and there is nothing left to do within `meson-python`. So let's close this. Of course if someone wants to push the issue in `pip`, that'd be useful.

**Closed by rgommers** 2023-04-18 15:02 UTC
Labels: question
