### ISSUE TITLE
All configuration keys must be set if any are set

### ISSUE THREAD

**Issue by ngoldbaum** [mesonbuild/meson-python#305] opened 2023-02-09 18:31 UTC
Currently, if one has a `pyproject.toml` that looks like:

```
[tool.meson-python.args]
setup = ["-Ddebug=true", "-Doptimization=0"]
```

Then at build time `meson-python` will raise an error:

```
meson-python: error: Unknown configuration key "tool.meson-python.args.dist"
```

A workaround is to set empty values for all supported configuration options:

```
[tool.meson-python.args]
dist = []
setup = ["-Ddebug=true", "-Doptimization=0"]
compile = []
install = []
```

It looks like the existing tests only use a `pyproject.toml` that has all four keys set.

**Comment by dnicolodi** [comment] 2023-02-09 18:33
Duplicate of #293. Fix waiting in #304.

**Closed by dnicolodi** 2023-02-09 18:33 UTC
